class Brick {
    constructor(fname, lname, branch, conflict) {
        this.fname = fname;
        this.lname = lname;
        this.branch = branch;
        this.conflict = conflict;
    }
}

const m = 72,
    n = 160;

const TEST = "76-26";

// prettier-ignore
const BRICKS = {
    "67-2": new Brick("NATHAN", "SUMMERS", "U S ARMY", "VIETNAM WAR"),
    "72-4": new Brick("BARRY D", "NOLL", "U S ARMY", ""),
    "73-5": new Brick("DEAN L", "NOLL", "U S ARMY", "WORLD WAR II"),
    "75-6": new Brick("ROGER A KENO", "WERT", "US ARMY", "VIETNAM ERA"),
    "77-4": new Brick("CARL OWEN", "REITZ", "U S ARMY", "WORLD WAR II"),
    "78-3": new Brick("MYRON W", "REITZ", "U S ARMY AIR CORPS", "WORLD WAR II"),
    "71-8": new Brick("MICHAEL", "CARPER", "U S ARMY", "VIETNAM WAR"),
    "72-8": new Brick("LAWRENCE", "CONDO", "U S ARMY", "WORLD WAR II"),
    "67-12": new Brick("JOHN", "BURGER", "U S AIR FORCE", ""),
    "74-11": new Brick("MATTHEW", "PARR", "U S NAVY", "IRAQI FREEDOM"),
    "75-12": new Brick("GEFFREY", "MOYER", "U S ARMY", ""),
    "74-15": new Brick("JEFF", "STRUBLE", "U S AIR FORCE", "VIETNAM WAR"),
    "72-22": new Brick("HARRY G", "BRANDT", "U S ARMY", "WORLD WAR II"),
    "73-23": new Brick("RICHARD", "WHITMAN", "U S AIR FORCE", "WORLD WAR II"),
    "66-23": new Brick("PETE", "BANHOLZER", "U S MARINE CORPS", "KOREAN WAR"),
    "68-26": new Brick("GENE", "McCOOL", "U S ARMY", ""),
    "60-23": new Brick("ROBERT C", "SMITH", "US AIR FORCE", ""),
    "60-26": new Brick("DONALD", "ROTE JR", "U S MARINE CORPS", "KOREAN WAR"),
    "59-23": new Brick("CHARLES B", "SMITH", "US ARMY", "WORLD WAR I"),
    "58-22": new Brick("CARL D", "SMITH", "US ARMY", "KOREAN WAR"),
    "58-23": new Brick("JOHN W", "ZERBY", "US ARMY", ""),
    "59-24": new Brick("DONALD E", "SMITH", "US ARMY AIR CORPS", "WORLD WAR II"),
    "57-21": new Brick("GEORGE", "MARTZ", "U S ARMY", "WORLD WAR II"),
    "55-24": new Brick("WILLIS H", "YARNELL", "U S NAVY", "WORLD WAR II"),
    "50-24": new Brick("HARRY R", "SPEER", "US NAVY", "WORLD WAR II"),
    "48-22": new Brick("DON", "FOUST", "U S ARMY AIR CORPS", "WORLD WAR II"),
    "52-18": new Brick("FLOYD W", "DASHEM", "U S ARMY", "WORLD WAR II"),
    "56-16": new Brick("KENNETH", "FRAZIER", "U S ARMY", "WORLD WAR II"),
    "53-13": new Brick("A EDGAR", "RIMMEY", "U S AIR FORCE", ""),
    "48-16": new Brick("GERALD L", "PIFER", "U S NAVY", "KOREAN WAR"),
    "49-13": new Brick("IRVIN A", "KANE", "AAC & USAF", "WORLD WAR II"),
    "53-9": new Brick("DONALD", "REFFNER", "U S ARMY", "WORLD WAR II"),
    "47-10": new Brick("GARY L", "WAY", "U S ARMY", "VIETNAM WAR"),
    "46-9": new Brick("VERIS C", "WAY", "U S ARMY AIR CORPS", "WORLD WAR II"),
    "45-9": new Brick("ROBERT H", "BARNES", "U S ARMY", "WORLD WAR II"),
    "40-8": new Brick("RICHARD W", "EVANS", "US ARMY", "WORLD WAR II"),
    "39-12": new Brick("BERNARD D", "JOYCE", "U S ARMY", "WORLD WAR II"),
    "38-12": new Brick("WALTER I", "JOYCE", "U S NAVY", "WORLD WAR II"),
    "37-12": new Brick("JACK", "JOYCE", "U S COAST GUARD", "WORLD WAR II"),
    "34-11": new Brick("KEVIN L", "WENRICK", "U S NAVY", ""),
    "41-15": new Brick("JAMES L", "SHUEY JR", "U S ARMY", ""),
    "40-16": new Brick("ROBERT", "KLINE", "U S ARMY", ""),
    "44-18": new Brick("BOB", "TIMNEY", "U S ARMY", "IRAQI FREEDOM"),
    "35-16": new Brick("WILLIAM", "WOLFE", "US ARMY", "PERSIAN GULF"),
    "32-14": new Brick("JOHN C", "SHOOK", "U S ARMY", "WORLD WAR II"),
    "26-15": new Brick("LOWELL", "JOHNSON", "U S ARMY", "IRAQI FREEDOM"),
    "25-15": new Brick("WALTER", "JOHNSON", "U S NAVY", "KOREAN WAR"),
    "24-14": new Brick("LEROY", "JOHNSON", "US ARMY US NAVY", "WWI    WWII"),
    "29-19": new Brick("CHALMER", "WEAVER", "U S ARMY", "WORLD WAR II"),
    "20-18": new Brick("GERALD M", "JOHNSON", "U S NAVY", "W W II, KOREAN WAR"),
    "27-22": new Brick("GEORGE", "STRICKLER", "U S ARMY", "WORLD WAR II"),
    "26-22": new Brick("WILLIAM H.", "HICKS", "U S AIR FORCE", "VIETNAM WAR"),
    "25-23": new Brick("KEN L", "GUISEWITE", "U S ARMY", "VIETNAM WAR"),
    "26-23": new Brick("LESTER", "GUISEWITE", "U S NAVY", "WORLD WAR II"),
    "27-23": new Brick("STEVEN D.", "CONDO", "U S ARMY", "VIETNAM WAR"),
    "27-24": new Brick("LARRY", "GUISEWITE", "U S ARMY", "VIETNAM WAR"),
    "30-21": new Brick("RAYMOND R", "COURSEN", "US ARMY", "VIETNAM WAR"),
    "18-21": new Brick("ROBERT E.", "HARMAN", "US ARMY", "WORLD WAR II"),
    "22-25": new Brick("WARREN L", "FOUST", "U S ARMY", "WORLD WAR II"),
    "14-23": new Brick("LOUISE", "POCHYBA", "U S ARMY", "WORLD WAR II"),
    "15-24": new Brick("SUSAN L", "POCHYBA", "U S NAVY", "VIETNAM ERA"),
    "15-26": new Brick("LEO N", "BRINDEL", "US NAVY", ""),
    "16-26": new Brick("DOUGLAS", "BRINDEL", "U S ARMY", "VIETNAM WAR"),
    "12-26": new Brick("LEWIS H", "FAUST", "U S ARMY", "WORLD WAR II"),
    "13-29": new Brick("LESLIE", "KLINE", "U S ARMY", "KOREAN WAR"),
    "12-30": new Brick("DAVE", "PANKO", "U S ARMY", ""),
    "9-29": new Brick("MYLAN E", "GROVE", "U S NAVY", "WORLD WAR II"),
    "8-28": new Brick("JAMES T", "GROVE", "U S MARINE CORPS", ""),
    "7-28": new Brick("WAYNE E", "GROVE", "U S ARMY", ""),
    "14-31": new Brick("JOEL W", "BURD", "U S NAVY", "VIETNAM WAR"),
    "18-29": new Brick("RONALD I", "MAUK", "U S ARMY AIR CORPS", "WORLD WAR II"),
    "6-31": new Brick("ALBERT", "YOUNG", "U S AIR FORCE", "KOREAN WAR"),
    "15-34": new Brick("WALTER S.", "BAILEY", "US NAVY", "VIETNAM WAR"),
    "12-34": new Brick("KENNETH R", "GIBB", "U S ARMY", "VIETNAM ERA"),
    "9-34": new Brick("WILLIAM", "NEESE", "U S ARMY", "VIETNAM ERA"),
    "13-37": new Brick("WILLIAM C", "LOOP", "U S MARINE CORPS", "VIETNAM WAR"),
    "4-34": new Brick("HALLARD", "ZETTLE", "US MARINE CORPS", "WORLD WAR II"),
    "5-35": new Brick("EARL R", "LEEDY", "US AIR FORCE", "VIETNAM ERA"),
    "6-35": new Brick("RONALD E", "LEEDY", "US ARMY", ""),
    "4-35": new Brick("JOHN L", "LEEDY", "US ARMY", ""),
    "3-35": new Brick("JAMES T", "LEEDY", "US NAVY", "VIETNAM WAR"),
    "2-34": new Brick("EARL C", "WEBER", "U S ARMY", "WORLD WAR I"),
    "2-35": new Brick("EARL", "ZETTLE", "U S ARMY", "WORLD WAR II"),
    "3-36": new Brick("ANTHONY W", "LEEDY", "US MARINES", "VIETNAM WAR"),
    "4-36": new Brick("MIKE LEEDY", "JOHNSON", "U S AIR FORCE", "VIETNAM ERA"),
    "3-38": new Brick("JOHN R", "ROSE", "U S MARINE CORPS", "WORLD WAR II, MIA"),
    "8-38": new Brick("DAVID V", "NEESE", "U S NAVY", "VIETNAM WAR"),
    "10-39": new Brick("KEITH", "LAUDERBACH", "U S ARMY", "VIETNAM WAR"),
    "11-40": new Brick("MYRON E", "BROWN", "U S ARMY", "VIETNAM ERA"),
    "11-39": new Brick("RALPH M", "ARNEY", "U S ARMY", "WORLW WAR II"),
    "12-40": new Brick("JACOB", "FRYER", "US ARMY", "VIETNAM ERA"),
    "7-42": new Brick("RONALD", "YOST", "US AIR FORCE", ""),
    "3-42": new Brick("NATHANIEL", "BROWN", "U S ARMY", "CIVIL WAR"),
    "10-43": new Brick("GLENN H", "RIDER", "U S ARMY", "WORLD WAR II"),
    "11-44": new Brick("VAN M", "JODON", "U S NAVY", "VIETNAM WAR"),
    "8-46": new Brick("HAROLD", "STAHL JR", "U S MARINE CORPS", "VIETNAM"),
    "13-47": new Brick("PAUL H", "MARQUARDT", "U S ARMY", ""),
    "9-49": new Brick("JACK L", "JOHNSON", "US AIR FORCE", "KOREAN WAR"),
    "14-50": new Brick("DONALD E.", "WILKINS", "US ARMY", "VIETNAM WAR"),
    "18-49": new Brick("LYNN E", "DUTROW", "U S ARMY", ""),
    "16-52": new Brick("BRUCE", "HARSHBARGER", "US ARMY", "WORLD WAR II"),
    "18-53": new Brick("ROBERT C", "LINGLE JR", "US AIR FORCE", "VIETNAM WAR"),
    "20-56": new Brick("WILLIAM R", "CORSON", "US NAVY", "KOREAN WAR"),
    "23-52": new Brick("PHIL", "RISHEL", "US MARINE CORPS", "IRAQI FREEDOM"),
    "24-54": new Brick("ED", "JOHNSTONBAUGH", "US NAVY", "WORLD WAR II"),
    "21-59": new Brick("LARRY R", "BURD", "US ARMY", "VIETNAM WAR"),
    "24-58": new Brick("ERNEST", "LONG JR", "U S AIR FORCE", "VIETNAM ERA"),
    "26-59": new Brick("RONALD", "McMAHON", "U S ARMY", "VIETNAM ERA"),
    "30-57": new Brick("JERRY A", "MYERS", "U S NAVY", "VIETNAM WAR"),
    "35-60": new Brick("JAMES E", "KELLER", "US ARMY AIR CORPS", "WORLD WAR II"),
    "36-60": new Brick("JAMES A.C.", "HALL", "US ARMY", "IRAQI FREEDOM"),
    "34-60": new Brick("WAYNE E", "KELLER JR", "US AIR FORCE", "WORLD WAR II"),
    "39-58": new Brick("GERALD K", "MOYER", "U S ARMY", "KOREAN WAR"),
    "43-64": new Brick("GEORGE R", "LESLIE", "U S ARMY", "WORLD WAR II"),
    "44-64": new Brick("BUTCH", "VONADA", "U S AIR FORCE", ""),
    "45-61": new Brick("LARRY L", "BARBOUR", "U S ARMY", "PERSIAN GULF"),
    "49-63": new Brick("ROBERT", "KEENE", "US MARINE CORPS", "VIETNAM WAR"),
    "49-65": new Brick("GEORGE", "MOCK", "U S COAST GUARD", "VIETNAM WAR"),
    "51-64": new Brick("FRED O", "BENNER", "U S ARMY", "KOREAN WAR"),
    "55-66": new Brick("RUSSELL", "SPADE", "U S ARMY", "WORLD WAR II"),
    "56-60": new Brick("HAROLD", "STITZER", "U S ARMY", "WORLD WAR II"),
    "51-60": new Brick("MAX O", "FULTZ", "U S ARMY", "WORLD WAR II"),
    "44-58": new Brick("RICHARD", "DUNKLE", "U S ARMY", "VIETNAM WAR"),
    "43-58": new Brick("BLAINE J", "DUNKLE", "U S ARMY", "WORLD WAR II"),
    "47-56": new Brick("HAROLD E", "GRAMLEY", "U S AIR FORCE", ""),
    "48-53": new Brick("RON", "SUMMERS", "USMC & US ARMY", "VIETNAM WAR"),
    "53-55": new Brick("EDGAR A", "TREASTER", "U S NAVY", "VIETNAM WAR"),
    "53-53": new Brick("CLARENCE", "CRATER", "U S ARMY", "WORLD WAR II"),
    "43-54": new Brick("C S", "HOSTERMAN JR", "US ARMY AIR CORPS", "WORLD WAR II"),
    "46-51": new Brick("RAYMOND", "MUSSER", "US ARMY", "WORLD"),
    "52-50": new Brick("RUSS", "SCHLEIDEN", "U S AIR FORCE", "VIETNAM WAR"),
    "51-48": new Brick("RONALD", "SCHAEFFER", "U S ARMY", "VIETNAM WAR"),
    "46-47": new Brick("RYAN A", "HELTMAN", "U S ARMY", ""),
    "59-48": new Brick("BEN C", "BAILEY", "U S ARMY AIR CORPS", "WORLD WAR II"),
    "60-46": new Brick("WAYNE K.", "MILLER", "U S ARMY", "VIETNAM WAR"),
    "63-46": new Brick("CHARLES", "HASSINGER, SR", "U S ARMY", ""),
    "60-42": new Brick("FRANKLIN", "CARPER", "U S ARMY", ""),
    "67-48": new Brick("TIMOTHY", "ARCHER", "U S AIR FORCE", ""),
    "69-51": new Brick("JOHN W", "PUFF", "U S MARINE CORPS", "WORLD WAR II"),
    "71-48": new Brick("BOWIE", "MILLER", "US ARMY", "IRAQI FREEDOM"),
    "73-53": new Brick("MELVIN", "HOLLIER", "U S ARMY", "WORLD WAR II"),
    "76-50": new Brick("CHARLES", "WINGARD", "U S ARMY AIR CORPS", "WORLD WAR II"),
    "77-55": new Brick("TORRENCE", "BARNER", "U S AIR FORCE", "VIETNAM WAR"),
    "76-58": new Brick("ALLEN W", "LEASE", "U S NAVY", ""),
    "71-58": new Brick("GUST J", "MADERIA", "U S AIR FORCE", "KOREAN WAR"),
    "73-65": new Brick("HARYY", "HASSINGER", "U S NAVY & AIR FORCE", "WWII & KOREAN WAR"),
    "69-69": new Brick("JOHN R", "MERSINGER", "U S AIR FORCE", "VIETNAM ERA IS"),
    "74-69": new Brick("HARRY C", "VANADA JR", "U S ARMY", "KOREAN WAR"),
    "78-69": new Brick("JAMES H", "WILSON", "U S MARINE CORPS", ""),
    "74-47": new Brick("ROBERT D", "SMITH", "U S NAVY", "KOREAN WAR"),
    "72-44": new Brick("CHARLES", "ANDERSON JR", "U S AIR FORCE", ""),
    "71-44": new Brick("CHARLES", "ANDERSON", "U S ARMY", "WORLD WAR II"),
    "70-43": new Brick("THOMAS", "ANDERSON", "U S ARMY", "VIETNAM WAR"),
    "69-43": new Brick("ROBERT", "ANDERSON", "U S ARMY", "VIETNAM WAR"),
    "70-42": new Brick("STEPHEN", "ANDERSON", "US MARINE CORPS", ""),
    "75-44": new Brick("KIMBERLY A", "RIMMEY", "U S ARMY", "IRAQI FREEDOM"),
    "77-39": new Brick("NEVIN G", "HOMAN", "U S MARINE CORPS", "VIETNAM WAR"),
    "69-39": new Brick("DAVE I", "GRAYBILL", "U S ARMY", "WORLD WAR II"),
    "74-35": new Brick("JIM", "HIRONIMUS", "U S AIR FORCE", "VIETNAM WAR"),
    "75-32": new Brick("CHUCK", "NORRIS", "U S ARMY", "VIETNAM WAR"),
    "76-32": new Brick("KEITH", "NORRIS SR", "U S ARMY", "VIETNAM WAR"),
    "77-32": new Brick("NEVIN", "WALTERS", "U S ARMY", "WORLD WAR II"),
    "76-31": new Brick("ROBERT", "WALTERS SR", "U S AIR FORCE", "VIETNAM WAR"),
    "67-34": new Brick("RALPH L", "SHOPE JR", "U S ARMY", "KOREAN WAR"),
    "77-27": new Brick("WILLIAM B.", "HOMAN", "U. S. MARINE CORPS", "VIETNAM WAR"),
};
