class Brick {
    constructor(fname, lname, branch, conflict) {
        this.fname = fname;
        this.lname = lname;
        this.branch = branch;
        this.conflict = conflict;
    }
}

const m = 72,
    n = 160;

const TEST = "";

// prettier-ignore
const BRICKS = {
    "67-2": new Brick("NATHAN", "SUMMERS", "U S ARMY", "VIETNAM WAR"),
    "72-4": new Brick("BARRY D", "NOLL", "U S ARMY", ""),
    "73-5": new Brick("DEAN L", "NOLL", "U S ARMY", "WORLD WAR II"),
    "75-6": new Brick("ROGER A KENO", "WERT", "US ARMY", "VIETNAM ERA"),
    "77-4": new Brick("CARL OWEN", "REITZ", "U S ARMY", "WORLD WAR II"),
    "78-3": new Brick("MYRON W", "REITZ", "U S ARMY AIR CORPS", "WORLD WAR II"),
    "71-8": new Brick("MICHAEL", "CARPER", "U S ARMY", "VIETNAM WAR"),
    "72-8": new Brick("LAWRENCE", "CONDO", "U S ARMY", "WORLD WAR II"),
    "67-12": new Brick("JOHN", "BURGER", "U S AIR FORCE", ""),
    "74-11": new Brick("MATTHEW", "PARR", "U S NAVY", "IRAQI FREEDOM"),
    "75-12": new Brick("GEFFREY", "MOYER", "U S ARMY", ""),
    "74-15": new Brick("JEFF", "STRUBLE", "U S AIR FORCE", "VIETNAM WAR"),
    "72-22": new Brick("HARRY G", "BRANDT", "U S ARMY", "WORLD WAR II"),
    "73-23": new Brick("RICHARD", "WHITMAN", "U S AIR FORCE", "WORLD WAR II"),
    "66-23": new Brick("PETE", "BANHOLZER", "U S MARINE CORPS", "KOREAN WAR"),
    "68-26": new Brick("GENE", "McCOOL", "U S ARMY", ""),
    "60-23": new Brick("ROBERT C", "SMITH", "US AIR FORCE", ""),
    "60-26": new Brick("DONALD", "ROTE JR", "U S MARINE CORPS", "KOREAN WAR"),
    "59-23": new Brick("CHARLES B", "SMITH", "US ARMY", "WORLD WAR I"),
    "58-22": new Brick("CARL D", "SMITH", "US ARMY", "KOREAN WAR"),
    "58-23": new Brick("JOHN W", "ZERBY", "US ARMY", ""),
    "59-24": new Brick("DONALD E", "SMITH", "US ARMY AIR CORPS", "WORLD WAR II"),
    "57-21": new Brick("GEORGE", "MARTZ", "U S ARMY", "WORLD WAR II"),
    "55-24": new Brick("WILLIS H", "YARNELL", "U S NAVY", "WORLD WAR II"),
    "50-24": new Brick("HARRY R", "SPEER", "US NAVY", "WORLD WAR II"),
    "48-22": new Brick("DON", "FOUST", "U S ARMY AIR CORPS", "WORLD WAR II"),
    "52-18": new Brick("FLOYD W", "DASHEM", "U S ARMY", "WORLD WAR II"),
    "56-16": new Brick("KENNETH", "FRAZIER", "U S ARMY", "WORLD WAR II"),
    "53-13": new Brick("A EDGAR", "RIMMEY", "U S AIR FORCE", ""),
    "48-16": new Brick("GERALD L", "PIFER", "U S NAVY", "KOREAN WAR"),
    "49-13": new Brick("IRVIN A", "KANE", "AAC & USAF", "WORLD WAR II"),
    "53-9": new Brick("DONALD", "REFFNER", "U S ARMY", "WORLD WAR II"),
    "47-10": new Brick("GARY L", "WAY", "U S ARMY", "VIETNAM WAR"),
    "46-9": new Brick("VERIS C", "WAY", "U S ARMY AIR CORPS", "WORLD WAR II"),
    "45-9": new Brick("ROBERT H", "BARNES", "U S ARMY", "WORLD WAR II"),
    "40-8": new Brick("RICHARD W", "EVANS", "US ARMY", "WORLD WAR II"),
    "39-12": new Brick("BERNARD D", "JOYCE", "U S ARMY", "WORLD WAR II"),
    "38-12": new Brick("WALTER I", "JOYCE", "U S NAVY", "WORLD WAR II"),
    "37-12": new Brick("JACK", "JOYCE", "U S COAST GUARD", "WORLD WAR II"),
    "34-11": new Brick("KEVIN L", "WENRICK", "U S NAVY", ""),
    "41-15": new Brick("JAMES L", "SHUEY JR", "U S ARMY", ""),
    "40-16": new Brick("ROBERT", "KLINE", "U S ARMY", ""),
    "44-18": new Brick("BOB", "TIMNEY", "U S ARMY", "IRAQI FREEDOM"),
    "35-16": new Brick("WILLIAM", "WOLFE", "US ARMY", "PERSIAN GULF"),
    "32-14": new Brick("JOHN C", "SHOOK", "U S ARMY", "WORLD WAR II"),
    "26-15": new Brick("LOWELL", "JOHNSON", "U S ARMY", "IRAQI FREEDOM"),
    "25-15": new Brick("WALTER", "JOHNSON", "U S NAVY", "KOREAN WAR"),
    "24-14": new Brick("LEROY", "JOHNSON", "US ARMY US NAVY", "WWI    WWII"),
    "29-19": new Brick("CHALMER", "WEAVER", "U S ARMY", "WORLD WAR II"),
    "20-18": new Brick("GERALD M", "JOHNSON", "U S NAVY", "W W II, KOREAN WAR"),
    "27-22": new Brick("GEORGE", "STRICKLER", "U S ARMY", "WORLD WAR II"),
    "26-22": new Brick("WILLIAM H.", "HICKS", "U S AIR FORCE", "VIETNAM WAR"),
    "25-23": new Brick("KEN L", "GUISEWITE", "U S ARMY", "VIETNAM WAR"),
    "26-23": new Brick("LESTER", "GUISEWITE", "U S NAVY", "WORLD WAR II"),
    "27-23": new Brick("STEVEN D.", "CONDO", "U S ARMY", "VIETNAM WAR"),
    "27-24": new Brick("LARRY", "GUISEWITE", "U S ARMY", "VIETNAM WAR"),
    "28-24": new Brick("RODNEY", "GUISEWITE", "U S AIR FORCE", "VIETNAM ERA"),
    "28-23": new Brick("FRED", "KOCH", "US NAVY", "VIETNAM WAR"),
    "30-21": new Brick("RAYMOND R", "COURSEN", "US ARMY", "VIETNAM WAR"),
    "18-21": new Brick("ROBERT E.", "HARMAN", "US ARMY", "WORLD WAR II"),
    "22-25": new Brick("WARREN L", "FOUST", "U S ARMY", "WORLD WAR II"),
    "14-23": new Brick("LOUISE", "POCHYBA", "U S ARMY", "WORLD WAR II"),
    "15-24": new Brick("SUSAN L", "POCHYBA", "U S NAVY", "VIETNAM ERA"),
    "15-26": new Brick("LEO N", "BRINDEL", "US NAVY", ""),
    "16-26": new Brick("DOUGLAS", "BRINDEL", "U S ARMY", "VIETNAM WAR"),
    "12-26": new Brick("LEWIS H", "FAUST", "U S ARMY", "WORLD WAR II"),
    "13-29": new Brick("LESLIE", "KLINE", "U S ARMY", "KOREAN WAR"),
    "12-30": new Brick("DAVE", "PANKO", "U S ARMY", ""),
    "9-29": new Brick("MYLAN E", "GROVE", "U S NAVY", "WORLD WAR II"),
    "8-28": new Brick("JAMES T", "GROVE", "U S MARINE CORPS", ""),
    "7-28": new Brick("WAYNE E", "GROVE", "U S ARMY", ""),
    "14-31": new Brick("JOEL W", "BURD", "U S NAVY", "VIETNAM WAR"),
    "18-29": new Brick("RONALD I", "MAUK", "U S ARMY AIR CORPS", "WORLD WAR II"),
    "6-31": new Brick("ALBERT", "YOUNG", "U S AIR FORCE", "KOREAN WAR"),
    "15-34": new Brick("WALTER S.", "BAILEY", "US NAVY", "VIETNAM WAR"),
    "12-34": new Brick("KENNETH R", "GIBB", "U S ARMY", "VIETNAM ERA"),
    "9-34": new Brick("WILLIAM", "NEESE", "U S ARMY", "VIETNAM ERA"),
    "13-37": new Brick("WILLIAM C", "LOOP", "U S MARINE CORPS", "VIETNAM WAR"),
    "4-34": new Brick("HALLARD", "ZETTLE", "US MARINE CORPS", "WORLD WAR II"),
    "5-35": new Brick("EARL R", "LEEDY", "US AIR FORCE", "VIETNAM ERA"),
    "6-35": new Brick("RONALD E", "LEEDY", "US ARMY", ""),
    "4-35": new Brick("JOHN L", "LEEDY", "US ARMY", ""),
    "3-35": new Brick("JAMES T", "LEEDY", "US NAVY", "VIETNAM WAR"),
    "2-34": new Brick("EARL C", "WEBER", "U S ARMY", "WORLD WAR I"),
    "2-35": new Brick("EARL", "ZETTLE", "U S ARMY", "WORLD WAR II"),
    "3-36": new Brick("ANTHONY W", "LEEDY", "US MARINES", "VIETNAM WAR"),
    "4-36": new Brick("MIKE LEEDY", "JOHNSON", "U S AIR FORCE", "VIETNAM ERA"),
    "3-38": new Brick("JOHN R", "ROSE", "U S MARINE CORPS", "WORLD WAR II, MIA"),
    "8-38": new Brick("DAVID V", "NEESE", "U S NAVY", "VIETNAM WAR"),
    "10-39": new Brick("KEITH", "LAUDERBACH", "U S ARMY", "VIETNAM WAR"),
    "11-40": new Brick("MYRON E", "BROWN", "U S ARMY", "VIETNAM ERA"),
    "11-39": new Brick("RALPH M", "ARNEY", "U S ARMY", "WORLD WAR II"),
    "12-40": new Brick("JACOB", "FRYER", "US ARMY", "VIETNAM ERA"),
    "7-42": new Brick("RONALD", "YOST", "US AIR FORCE", ""),
    "3-42": new Brick("NATHANIEL", "BROWN", "U S ARMY", "CIVIL WAR"),
    "10-43": new Brick("GLENN H", "RIDER", "U S ARMY", "WORLD WAR II"),
    "11-44": new Brick("VAN M", "JODON", "U S NAVY", "VIETNAM WAR"),
    "8-46": new Brick("HAROLD", "STAHL JR", "U S MARINE CORPS", ""),
    "13-47": new Brick("PAUL H", "MARQUARDT", "U S ARMY", ""),
    "9-49": new Brick("JACK L", "JOHNSON", "US AIR FORCE", "KOREAN WAR"),
    "14-50": new Brick("DONALD E.", "WILKINS", "US ARMY", "VIETNAM WAR"),
    "18-49": new Brick("LYNN E", "DUTROW", "U S ARMY", ""),
    "16-52": new Brick("BRUCE", "HARSHBARGER", "US ARMY", "WORLD WAR II"),
    "18-53": new Brick("ROBERT C", "LINGLE JR", "US AIR FORCE", "VIETNAM WAR"),
    "20-56": new Brick("WILLIAM R", "CORSON", "US NAVY", "KOREAN WAR"),
    "23-52": new Brick("PHIL", "RISHEL", "US MARINE CORPS", "IRAQI FREEDOM"),
    "24-54": new Brick("ED", "JOHNSTONBAUGH", "US NAVY", "WORLD WAR II"),
    "21-59": new Brick("LARRY R", "BURD", "US ARMY", "VIETNAM WAR"),
    "24-58": new Brick("ERNEST", "LONG JR", "U S AIR FORCE", "VIETNAM ERA"),
    "26-59": new Brick("RONALD", "McMAHON", "U S ARMY", "VIETNAM ERA"),
    "30-57": new Brick("JERRY A", "MYERS", "U S NAVY", "VIETNAM WAR"),
    "35-60": new Brick("JAMES E", "KELLER", "US ARMY AIR CORPS", "WORLD WAR II"),
    "36-60": new Brick("JAMES A.C.", "HALL", "US ARMY", "IRAQI FREEDOM"),
    "34-60": new Brick("WAYNE E", "KELLER JR", "US AIR FORCE", "WORLD WAR II"),
    "39-58": new Brick("GERALD K", "MOYER", "U S ARMY", "KOREAN WAR"),
    "43-64": new Brick("GEORGE R", "LESLIE", "U S ARMY", "WORLD WAR II"),
    "44-64": new Brick("BUTCH", "VONADA", "U S AIR FORCE", ""),
    "45-61": new Brick("LARRY L", "BARBOUR", "U S ARMY", "PERSIAN GULF"),
    "49-63": new Brick("ROBERT", "KEENE", "US MARINE CORPS", "VIETNAM WAR"),
    "49-65": new Brick("GEORGE", "MOCK", "U S COAST GUARD", "VIETNAM WAR"),
    "51-64": new Brick("FRED O", "BENNER", "U S ARMY", "KOREAN WAR"),
    "55-66": new Brick("RUSSELL", "SPADE", "U S ARMY", "WORLD WAR II"),
    "56-60": new Brick("HAROLD", "STITZER", "U S ARMY", "WORLD WAR II"),
    "51-60": new Brick("MAX O", "FULTZ", "U S ARMY", "WORLD WAR II"),
    "44-58": new Brick("RICHARD", "DUNKLE", "U S ARMY", "VIETNAM WAR"),
    "43-58": new Brick("BLAINE J", "DUNKLE", "U S ARMY", "WORLD WAR II"),
    "47-56": new Brick("HAROLD E", "GRAMLEY", "U S AIR FORCE", ""),
    "48-53": new Brick("RON", "SUMMERS", "USMC & US ARMY", "VIETNAM WAR"),
    "53-55": new Brick("EDGAR A", "TREASTER", "U S NAVY", "VIETNAM WAR"),
    "53-53": new Brick("CLARENCE", "CRATER", "U S ARMY", "WORLD WAR II"),
    "43-54": new Brick("C S", "HOSTERMAN JR", "US ARMY AIR CORPS", "WORLD WAR II"),
    "46-51": new Brick("RAYMOND", "MUSSER", "US ARMY", ""),
    "52-50": new Brick("RUSS", "SCHLEIDEN", "U S AIR FORCE", "VIETNAM WAR"),
    "51-48": new Brick("RONALD", "SCHAEFFER", "U S ARMY", "VIETNAM WAR"),
    "46-47": new Brick("RYAN A", "HELTMAN", "U S ARMY", ""),
    "59-48": new Brick("BEN C", "BAILEY", "U S ARMY AIR CORPS", "WORLD WAR II"),
    "60-46": new Brick("WAYNE K.", "MILLER", "U S ARMY", "VIETNAM WAR"),
    "63-46": new Brick("CHARLES", "HASSINGER, SR", "U S ARMY", ""),
    "60-42": new Brick("FRANKLIN", "CARPER", "U S ARMY", ""),
    "67-48": new Brick("TIMOTHY", "ARCHER", "U S AIR FORCE", ""),
    "69-51": new Brick("JOHN W", "PUFF", "U S MARINE CORPS", "WORLD WAR II"),
    "71-48": new Brick("BOWIE", "MILLER", "US ARMY", "IRAQI FREEDOM"),
    "73-53": new Brick("MELVIN", "HOLLIER", "U S ARMY", "WORLD WAR II"),
    "76-50": new Brick("CHARLES", "WINGARD", "U S ARMY AIR CORPS", "WORLD WAR II"),
    "77-55": new Brick("TORRENCE", "BARNER", "U S AIR FORCE", "VIETNAM WAR"),
    "76-58": new Brick("ALLEN W", "LEASE", "U S NAVY", ""),
    "71-58": new Brick("GUST J", "MADERIA", "U S AIR FORCE", "KOREAN WAR"),
    "73-65": new Brick("HARYY", "HASSINGER", "U S NAVY & AIR FORCE", "WWII & KOREAN WAR"),
    "69-69": new Brick("JOHN R", "MERSINGER", "U S AIR FORCE", "VIETNAM ERA IS"),
    "74-69": new Brick("HARRY C", "VANADA JR", "U S ARMY", "KOREAN WAR"),
    "78-69": new Brick("JAMES H", "WILSON", "U S MARINE CORPS", ""),
    "74-47": new Brick("ROBERT D", "SMITH", "U S NAVY", "KOREAN WAR"),
    "72-44": new Brick("CHARLES", "ANDERSON JR", "U S AIR FORCE", ""),
    "71-44": new Brick("CHARLES", "ANDERSON", "U S ARMY", "WORLD WAR II"),
    "70-43": new Brick("THOMAS", "ANDERSON", "U S ARMY", "VIETNAM WAR"),
    "69-43": new Brick("ROBERT", "ANDERSON", "U S ARMY", "VIETNAM WAR"),
    "70-42": new Brick("STEPHEN", "ANDERSON", "US MARINE CORPS", ""),
    "75-44": new Brick("KIMBERLY A", "RIMMEY", "U S ARMY", "IRAQI FREEDOM"),
    "77-39": new Brick("NEVIN G", "HOMAN", "U S MARINE CORPS", "VIETNAM WAR"),
    "69-39": new Brick("DAVE I", "GRAYBILL", "U S ARMY", "WORLD WAR II"),
    "74-35": new Brick("JIM", "HIRONIMUS", "U S AIR FORCE", "VIETNAM WAR"),
    "75-32": new Brick("CHUCK", "NORRIS", "U S ARMY", "VIETNAM WAR"),
    "76-32": new Brick("KEITH", "NORRIS SR", "U S ARMY", "VIETNAM WAR"),
    "77-32": new Brick("NEVIN", "WALTERS", "U S ARMY", "WORLD WAR II"),
    "76-31": new Brick("ROBERT", "WALTERS SR", "U S AIR FORCE", "VIETNAM WAR"),
    "68-34": new Brick("RALPH L", "SHOPE JR", "U S ARMY", "KOREAN WAR"),
    "77-27": new Brick("WILLIAM B.", "HOMAN", "U. S. MARINE CORPS", "VIETNAM WAR"),
    "66-29": new Brick("RUSSELL", "LEONARD", "U S ARMY", "VIETNAM WAR"),
    "61-31": new Brick("GRIER C", "BARBOUR", "U S AIR AIR CORPS", "WORLD WAR II"),
    "58-33": new Brick("CAROL A.", "CLARK-BANEY", "US ARMY", ""),
    "58-29": new Brick("IRWIN", "RHODE", "US MARINE CORPS", "VIETNAM WAR"),
    "54-29": new Brick("THOMAS", "HEVERLY", "US NAVY", "VIETNAM WAR"),
    "52-28": new Brick("LLOYD L", "WENRICK", "U S ARMY", "VIETNAM WAR"),
    "47-30": new Brick("THOMAS S.", "STONER", "U S ARMY", ""),
    "46-29": new Brick("HAROLD", "SAMPSELL", "U S ARMY", "VIETNAM WAR"),
    "40-22": new Brick("PHILIP", "BRADFORD", "U S ARMY", "KOREAN WAR"),
    "39-22": new Brick("HAROLD", "BRADFORD", "U S NAVY", "WORLD WAR II"),
    "41-25": new Brick("JAMES D", "YOUNG", "U S NAVY", "W W II & KOREA"),
    "41-27": new Brick("C L \"FAT\"", "PRICE", "U S NAVY", "WORLD WAR II"),
    "42-27": new Brick("DENNIS", "PRICE", "U S NAVY", "VIETNAM WAR"),
    "43-28": new Brick("MARVIN", "PRICE", "U S NAVY", "WORLD WAR II"),
    "40-27": new Brick("EUGENE I", "PRICE", "U S MARINE CORPS", "WORLD WAR II"),
    "41-28": new Brick("WILLIAM W.", "STUTER", "U S MARINE CORPS", ""),
    "42-28": new Brick("R DALE", "SHIELDS", "ARMY AIR CORPS", "WORLD WAR II"),
    "40-19": new Brick("WILLIAM C", "SCHULTZ", "US ARMY", "KOREAN WAR"),
    "37-19": new Brick("JAMES M", "COLE", "U S ARMY", ""),
    "35-22": new Brick("VINTON H", "LINGLE", "U S NAVY", "WORLD WAR II"),
    "34-25": new Brick("MAHLON", "McMURTRIE", "US MARINE CORPS", "VIETNAM WAR"),
    "29-27": new Brick("KENNETH E", "HAUPT SR", "U S ARMY", "KOREAN WAR"),
    "32-28": new Brick("LARRY H", "YOUNG", "U S ARMY", "VIETNAM WAR"),
    "33-29": new Brick("KEN", "SPANGLER", "U S ARMY", "VIETNAM WAR"),
    "24-28": new Brick("BUDD L", "HOY", "U S ARMY", "WW II & KOREAN WAR"),
    "18-31": new Brick("WALTER", "MAYES", "US MARINE CORPS", "KOREAN WAR"),
    "19-32": new Brick("MICHAEL", "MAYES", "U S ARMY", "IRAQI FREEDOM"),
    "20-32": new Brick("RONALD", "MAYES SR", "U.S.M.C", "VIETNAM ERA"),
    "21-33": new Brick("DONALD R", "MAYES", "U S ARMY", "KOREAN WAR"),
    "20-34": new Brick("KENNETH", "BOWER", "U S AIR FORCE", "KOREAN WAR"),
    "18-37": new Brick("RALPH E", "LONG", "U S ARMY", "WORLD WAR II"),
    "20-38": new Brick("DONALD", "FETTEROLF", "U S AIR FORCE", "KOREAN WAR"),
    "21-38": new Brick("DENNIS W", "ROYER", "U S ARMY", "VIETNAM WAR"),
    "21-39": new Brick("GLENN C", "DERSHEM", "U S NAVY", "WORLD WAR II"),
    "19-39": new Brick("WILLARD T", "ROYER", "U S ARMY", "WORLD WAR II"),
    "20-39": new Brick("GEARHARD", "ROYER", "U S ARMY", ""),
    "12-39": new Brick("JUSTIN", "WITHERITE", "U S ARMY", ""),
    "13-40": new Brick("HARRY M", "BROWN", "U S ARMY", "WORLD WAR II"),
    "13-41": new Brick("ROY C", "HOMAN", "U S ARMY", ""),
    "18-43": new Brick("LEWIS", "GARBRICK", "U S NAVY", "WORLD WAR II"),
    "20-46": new Brick("FRED", "BURLINGAME", "U S ARMY AIR CORPS", "WORLD WAR II"),
    "25-47": new Brick("CHARLES H", "ORT", "U S NAVY", "WORLD WAR II"),
    "27-44": new Brick("C EUGENE", "DUTROW", "US ARMY", "KOREAN WAR"),
    "22-49": new Brick("WILLIAM", "ALLISON", "U S NAVY", "VIETNAM WAR"),
    "29-47": new Brick("LEE S", "HALL", "U S ARMY", "WORLD WAR II"),
    "30-47": new Brick("A R", "McNITT", "U S ARMY", "KOREAN WAR"),
    "31-48": new Brick("JOHN D", "KNARR", "U S ARMY", "WORLD WAR II"),
    "27-49": new Brick("PHILLIP", "CRAUL", "U S ARMY", ""),
    "29-51": new Brick("LARRY R", "MOYER", "U S AIR FORCE", "VIETNAM WAR"),
    "30-53": new Brick("CLARENCE", "OAKES", "U S MARINE CORPS", "VIETNAM WAR"),
    "33-51": new Brick("JOHN", "NWRANSKI", "U S ARMY", "WORLD WAR II"),
    "34-54": new Brick("MICHAEL", "MUSSER", "U S AIR FORCE", "PERSIAN GULF"),
    "33-56": new Brick("RICHARD", "RUNKLE", "US AIR FORCE", "KOREAN WAR"),
    "38-53": new Brick("RICHARD E", "SMALLEY", "U S ARMY", "KOREAN WAR"),
    "42-49": new Brick("J. E.", "CHIOVAROU", "U S NAVY", ""),
    "52-44": new Brick("MICHAEL", "WENRICK", "U S ARMY", "IRAQI FREEDOM"),
    "53-45": new Brick("W \"BUCK\"", "WENRICK", "U S ARMY", ""),
    "54-45": new Brick("MAURICE", "NEWMAN", "U S MARINE CORPS", "VIETNAM WAR"),
    "55-46": new Brick("CLYDE", "BOYER", "U S ARMY", "WORLD WAR II"),
    "49-43": new Brick("NICK", "LESNIAK", "U S ARMY", ""),
    "50-42": new Brick("STAN", "LESNIAK", "U S ARMY & NAVY", ""),
    "67-42": new Brick("MICHAEL P", "McDERMOTT", "U S NAVY", ""),
    "64-40": new Brick("MIKE", "McCLENAHAN", "US ARMY", "KOREAN WAR"),
    "63-40": new Brick("ROBIN", "McCLENAHAN", "US ARMY", ""),
    "63-39": new Brick("PAT", "McCLENAHAN", "U S ARMY", ""),
    "64-39": new Brick("MILES W", "WOLFE", "U S ARMY", "WORLD WAR II"),
    "62-37": new Brick("TERRY L", "ALEXANDER", "U S ARMY", "VIETNAM WAR"),
    "51-31": new Brick("TIM TR", "ROSS", "U S ARMY", "VIETNAM ERA"),
    "50-31": new Brick("ROBERT S.", "ROSS", "U S ARMY AIR CORPS", "WORLD WAR II"),
    "51-32": new Brick("ARDELL", "GROSS SR", "U S NAVY", "WORLD WAR II"),
    "42-31": new Brick("JOHN I", "STONER", "U S ARMY", "VIETNAM WAR"),
    "38-32": new Brick("LEWIS A", "CRADER", "U S ARMY", "WORLD WAR 1"),
    "40-32": new Brick("HAROLD", "WINGARD", "US AIR FORCE", "VIETNAM WAR"),
    "39-33": new Brick("DOYLE", "WINGARD", "U S NAVY", "WORLD WAR II"),
    "41-33": new Brick("HENRY", "WINGARD", "U S ARMY", "WORLD WAR II"),
    "42-33": new Brick("JAY", "WINGARD", "ARMY AIR CORPS", "WORLD WAR II"),
    "43-34": new Brick("STUART", "WINGARD", "U S ARMY", "WORLD WAR II"),
    "44-34": new Brick("ALLEN R", "WINGARD", "U S ARMY", "WORLD WAR 1"),
    "36-32": new Brick("TIMOTH R", "LAKE", "U S NAVY", "PERSIAN GULF"),
    "35-32": new Brick("MIKE", "LAKE", "U S ARMY", "VIETNAM WAR"),
    "33-31": new Brick("ROY K", "DUNKLEBARGER", "U S ARMY", "WORLD WAR II"),
    "30-31": new Brick("GEO RUSS", "SMITH", "U S AIR FORCE", "KOREAN WAR"),
    "24-32": new Brick("LEE C", "DORMAN", "U S NAVY", ""),
    "23-35": new Brick("NEVIN E", "LONG", "U S ARMY", ""),
    "26-37": new Brick("RAYMOND", "MUSSER", "U S ARMY", "WORLD WAR II"),
    "30-39": new Brick("STEPHEN L", "FOUST", "U S ARMY", "VIETNAM ERA"),
    "33-35": new Brick("GLENN", "BRESSLER", "U S ARMY", "WORLD WAR II"),
    "34-35": new Brick("DENNIS", "BRESSLER", "U S ARMY", "VIETNAM WAR"),
    "35-36": new Brick("JAMES V", "SWALES", "U S ARMY", "WORLD WARD II"),
    "33-41": new Brick("RONALD J", "HORNER", "U S ARMY", "VIETNAM WAR"),
    "34-43": new Brick("DENNIS", "ROYER", "U S AIR FORCE", ""),
    "35-44": new Brick("DEAN B", "RIPKA", "U S ARMY", "WORLD WAR II"),
    "36-44": new Brick("KENNETH D", "ROYER", "U S AIR FORCE", "VIETNAM WAR"),
    "37-45": new Brick("PAUL A", "GROVE", "U S ARMY", "WORLD WAR II"),
    "38-45": new Brick("CARL W", "ROYER", "U S AIR FORCE", "KOREAN WAR"),
    "39-46": new Brick("SHANE", "ROYER", "U S ARMY", "PERSIAN GULF"),
    "40-46": new Brick("SHANE", "ROYER", "U S ARMY", "IRAQI FREEDOM"),
    "41-45": new Brick("ARTHUR", "RIDENOUR SR", "US MARINE CORPS", "VIETNAM WAR"),
    "38-49": new Brick("TERRY", "CHAMBERLIN", "U S ARMY", "VIETNAM ERA"),
    "45-43": new Brick("MAHLON D", "NEVEL", "U S ARMY", "WORLD WAR II"),
    "49-41": new Brick("WILLIAM E", "MILLS", "U S ARMY", "VIETNAM WAR"),
    "48-38": new Brick("ARDEL H", "VONADA KIA", "U S ARMY AIR CORPS", "WORLD WAR II"),
    "50-37": new Brick("HOBIE", "KISTLER", "U S NAVY", "NAVAL REACTORS"),
    "48-36": new Brick("STEPHEN", "KUCAS", "U S ARMY, KIA", "KOREAN & V-NAM WAR"),
    "46-37": new Brick("MICHAEL", "KRONER", "U S ARMY", "IRAQI FREEDOM, KIA"),
    "44-38": new Brick("CHESTER", "PLETCHER", "U S ARMY", "WORLD WAR II, KIA"),
    "44-36": new Brick("HAROLD W", "SMITH", "U S ARMY AIR CORPS", "WORLD WAR II, KIA"),
};
