class Brick {
    constructor(fname, lname, branch, branchIds, conflict, coords) {
        this.fname = fname;
        this.lname = lname;
        this.branch = branch;
        this.branchIds = branchIds;
        this.conflict = conflict;
        this.coords = coords;
    }

    getString() {
        let str = `${this.lname}, ${this.fname} `;

        const similarBricks = BRICKS.filter(
            (b) =>
                b !== this && b.fname === this.fname && b.lname === this.lname
        );

        if (this.branch && similarBricks.some((b) => b.branch !== this.branch))
            str += ` / ${this.branch}`;

        if (
            this.conflict &&
            similarBricks.some((b) => b.conflict !== this.conflict)
        )
            str += ` / ${this.conflict}`;

        return str;
    }
}

const m = 72,
    n = 160;

// prettier-ignore
const BRICKS = [
    new Brick("NATHAN", "SUMMERS", "ARMY", [1], "VIETNAM WAR", "67-2"),
    new Brick("BARRY D", "NOLL", "ARMY", [1], "", "72-4"),
    new Brick("DEAN L", "NOLL", "ARMY", [1], "WWII", "73-5"),
    new Brick("ROGER A KENO", "WERT", "ARMY", [1], "VIETNAM ERA", "75-6"),
    new Brick("CARL OWEN", "REITZ", "ARMY", [1], "WWII", "77-4"),
    new Brick("MYRON W", "REITZ", "ARMY AIR CORPS", [6], "WWII", "78-3"),
    new Brick("MICHAEL", "CARPER", "ARMY", [1], "VIETNAM WAR", "71-8"),
    new Brick("LAWRENCE", "CONDO", "ARMY", [1], "WWII", "72-8"),
    new Brick("JOHN", "BURGER", "AIR FORCE", [3], "", "67-12"),
    new Brick("MATTHEW", "PARR", "NAVY", [2], "IRAQI FREEDOM", "74-11"),
    new Brick("GEFFREY", "MOYER", "ARMY", [1], "", "75-12"),
    new Brick("JEFF", "STRUBLE", "AIR FORCE", [3], "VIETNAM WAR", "74-15"),
    new Brick("HARRY G", "BRANDT", "ARMY", [1], "WWII", "72-22"),
    new Brick("RICHARD", "WHITMAN", "AIR FORCE", [3], "WWII", "73-23"),
    new Brick("PETE", "BANHOLZER", "MARINE CORPS", [4], "KOREAN WAR", "66-23"),
    new Brick("GENE", "McCOOL", "ARMY", [1], "", "68-26"),
    new Brick("ROBERT C", "SMITH", "AIR FORCE", [3], "", "60-23"),
    new Brick("DONALD", "ROTE JR", "MARINE CORPS", [4], "KOREAN WAR", "60-26"),
    new Brick("CHARLES B", "SMITH", "ARMY", [1], "WWI", "59-23"),
    new Brick("CARL D", "SMITH", "ARMY", [1], "KOREAN WAR", "58-22"),
    new Brick("JOHN W", "ZERBY", "ARMY", [1], "", "58-23"),
    new Brick("DONALD E", "SMITH", "ARMY AIR CORPS", [6], "WWII", "59-24"),
    new Brick("GEORGE", "MARTZ", "ARMY", [1], "WWII", "57-21"),
    new Brick("WILLIS H", "YARNELL", "NAVY", [2], "WWII", "55-24"),
    new Brick("HARRY R", "SPEER", "NAVY", [2], "WWII", "50-24"),
    new Brick("DON", "FOUST", "ARMY AIR CORPS", [6], "WWII", "48-22"),
    new Brick("FLOYD W", "DASHEM", "ARMY", [1], "WWII", "52-18"),
    new Brick("KENNETH", "FRAZIER", "ARMY", [1], "WWII", "56-16"),
    new Brick("A EDGAR", "RIMMEY", "AIR FORCE", [3], "", "53-13"),
    new Brick("GERALD L", "PIFER", "NAVY", [2], "KOREAN WAR", "48-16"),
    new Brick("IRVIN A", "KANE", "AAC & AIR FORCE", [7, 3], "WWII", "49-13"),
    new Brick("DONALD", "REFFNER", "ARMY", [1], "WWII", "53-9"),
    new Brick("GARY L", "WAY", "ARMY", [1], "VIETNAM WAR", "47-10"),
    new Brick("VERIS C", "WAY", "ARMY AIR CORPS", [6], "WWII", "46-9"),
    new Brick("ROBERT H", "BARNES", "ARMY", [1], "WWII", "45-9"),
    new Brick("RICHARD W", "EVANS", "ARMY", [1], "WWII", "40-8"),
    new Brick("BERNARD D", "JOYCE", "ARMY", [1], "WWII", "39-12"),
    new Brick("WALTER I", "JOYCE", "NAVY", [2], "WWII", "38-12"),
    new Brick("JACK", "JOYCE", "COAST GUARD", [5], "WWII", "37-12"),
    new Brick("KEVIN L", "WENRICK", "NAVY", [2], "", "34-11"),
    new Brick("JAMES L", "SHUEY JR", "ARMY", [1], "", "41-15"),
    new Brick("ROBERT", "KLINE", "ARMY", [1], "", "40-16"),
    new Brick("BOB", "TIMNEY", "ARMY", [1], "IRAQI FREEDOM", "44-18"),
    new Brick("WILLIAM", "WOLFE", "ARMY", [1], "PERSIAN GULF", "35-16"),
    new Brick("JOHN C", "SHOOK", "ARMY", [1], "WWII", "32-14"),
    new Brick("LOWELL", "JOHNSON", "ARMY", [1], "IRAQI FREEDOM", "26-15"),
    new Brick("WALTER", "JOHNSON", "NAVY", [2], "KOREAN WAR", "25-15"),
    new Brick("LEROY", "JOHNSON", "ARMY & NAVY", [1, 2], "WWI & WWII", "24-14"),
    new Brick("CHALMER", "WEAVER", "ARMY", [1], "WWII", "29-19"),
    new Brick("GERALD M", "JOHNSON", "NAVY", [2], "WWII & KOREAN WAR", "20-18"),
    new Brick("GEORGE", "STRICKLER", "ARMY", [1], "WWII", "27-22"),
    new Brick("WILLIAM H", "HICKS", "AIR FORCE", [3], "VIETNAM WAR", "26-22"),
    new Brick("KEN L", "GUISEWITE", "ARMY", [1], "VIETNAM WAR", "25-23"),
    new Brick("LESTER", "GUISEWITE", "NAVY", [2], "WWII", "26-23"),
    new Brick("STEVEN D", "CONDO", "ARMY", [1], "VIETNAM WAR", "27-23"),
    new Brick("LARRY", "GUISEWITE", "ARMY", [1], "VIETNAM WAR", "27-24"),
    new Brick("RODNEY", "GUISEWITE", "AIR FORCE", [3], "VIETNAM ERA", "28-24"),
    new Brick("FRED", "KOCH", "NAVY", [2], "VIETNAM WAR", "28-23"),
    new Brick("RAYMOND R", "COURSEN", "ARMY", [1], "VIETNAM WAR", "30-21"),
    new Brick("ROBERT E", "HARMAN", "ARMY", [1], "WWII", "18-21"),
    new Brick("WARREN L", "FOUST", "ARMY", [1], "WWII", "22-25"),
    new Brick("LOUISE", "POCHYBA", "ARMY", [1], "WWII", "14-23"),
    new Brick("SUSAN L", "POCHYBA", "NAVY", [2], "VIETNAM ERA", "15-24"),
    new Brick("LEO N", "BRINDEL", "NAVY", [2], "", "15-26"),
    new Brick("DOUGLAS", "BRINDEL", "ARMY", [1], "VIETNAM WAR", "16-26"),
    new Brick("LEWIS H", "FAUST", "ARMY", [1], "WWII", "12-26"),
    new Brick("LESLIE", "KLINE", "ARMY", [1], "KOREAN WAR", "13-29"),
    new Brick("DAVE", "PANKO", "ARMY", [1], "", "12-30"),
    new Brick("MYLAN E", "GROVE", "NAVY", [2], "WWII", "9-29"),
    new Brick("JAMES T", "GROVE", "MARINE CORPS", [4], "", "8-28"),
    new Brick("WAYNE E", "GROVE", "ARMY", [1], "", "7-28"),
    new Brick("JOEL W", "BURD", "NAVY", [2], "VIETNAM WAR", "14-31"),
    new Brick("RONALD I", "MAUK", "ARMY AIR CORPS", [6], "WWII", "18-29"),
    new Brick("ALBERT", "YOUNG", "AIR FORCE", [3], "KOREAN WAR", "6-31"),
    new Brick("WALTER S", "BAILEY", "NAVY", [2], "VIETNAM WAR", "15-34"),
    new Brick("KENNETH R", "GIBB", "ARMY", [1], "VIETNAM ERA", "12-34"),
    new Brick("WILLIAM", "NEESE", "ARMY", [1], "VIETNAM ERA", "9-34"),
    new Brick("WILLIAM C", "LOOP", "MARINE CORPS", [4], "VIETNAM WAR", "13-37"),
    new Brick("HALLARD", "ZETTLE", "MARINE CORPS", [4], "WWII", "4-34"),
    new Brick("EARL R", "LEEDY", "AIR FORCE", [3], "VIETNAM ERA", "5-35"),
    new Brick("RONALD E", "LEEDY", "ARMY", [1], "", "6-35"),
    new Brick("JOHN L", "LEEDY", "ARMY", [1], "", "4-35"),
    new Brick("JAMES T", "LEEDY", "NAVY", [2], "VIETNAM WAR", "3-35"),
    new Brick("EARL C", "WEBER", "ARMY", [1], "WWI", "2-34"),
    new Brick("EARL", "ZETTLE", "ARMY", [1], "WWII", "2-35"),
    new Brick("ANTHONY W", "LEEDY", "MARINE CORPS", [4], "VIETNAM WAR", "3-36"),
    new Brick("MIKE LEEDY", "JOHNSON", "AIR FORCE", [3], "VIETNAM ERA", "4-36"),
    new Brick("JOHN R", "ROSE", "MARINE CORPS", [4], "WWII", "3-38"),
    new Brick("DAVID V", "NEESE", "NAVY", [2], "VIETNAM WAR", "8-38"),
    new Brick("KEITH", "LAUDERBACH", "ARMY", [1], "VIETNAM WAR", "10-39"),
    new Brick("MYRON E", "BROWN", "ARMY", [1], "VIETNAM ERA", "11-40"),
    new Brick("RALPH M", "ARNEY", "ARMY", [1], "WWII", "11-39"),
    new Brick("JACOB", "FRYER", "ARMY", [1], "VIETNAM ERA", "12-40"),
    new Brick("RONALD", "YOST", "AIR FORCE", [3], "", "7-42"),
    new Brick("NATHANIEL", "BROWN", "ARMY", [1], "CIVIL WAR", "3-42"),
    new Brick("GLENN H", "RIDER", "ARMY", [1], "WWII", "10-43"),
    new Brick("VAN M", "JODON", "NAVY", [2], "VIETNAM WAR", "11-44"),
    new Brick("HAROLD", "STAHL JR", "MARINE CORPS", [4], "", "8-46"),
    new Brick("PAUL H", "MARQUARDT", "ARMY", [1], "", "13-47"),
    new Brick("JACK L", "JOHNSON", "AIR FORCE", [3], "KOREAN WAR", "9-49"),
    new Brick("DONALD E", "WILKINS", "ARMY", [1], "VIETNAM WAR", "14-50"),
    new Brick("LYNN E", "DUTROW", "ARMY", [1], "", "18-49"),
    new Brick("BRUCE", "HARSHBARGER", "ARMY", [1], "WWII", "16-52"),
    new Brick("ROBERT C", "LINGLE JR", "AIR FORCE", [3], "VIETNAM WAR", "18-53"),
    new Brick("WILLIAM R", "CORSON", "NAVY", [2], "KOREAN WAR", "20-56"),
    new Brick("PHIL", "RISHEL", "MARINE CORPS", [4], "IRAQI FREEDOM", "23-52"),
    new Brick("ED", "JOHNSTONBAUGH", "NAVY", [2], "WWII", "24-54"),
    new Brick("LARRY R", "BURD", "ARMY", [1], "VIETNAM WAR", "21-59"),
    new Brick("ERNEST", "LONG JR", "AIR FORCE", [3], "VIETNAM ERA", "24-58"),
    new Brick("RONALD", "McMAHON", "ARMY", [1], "VIETNAM ERA", "26-59"),
    new Brick("JERRY A", "MYERS", "NAVY", [2], "VIETNAM WAR", "30-57"),
    new Brick("JAMES E", "KELLER", "ARMY AIR CORPS", [6], "WWII", "35-60"),
    new Brick("JAMES AC", "HALL", "ARMY", [1], "IRAQI FREEDOM", "36-60"),
    new Brick("WAYNE E", "KELLER JR", "AIR FORCE", [3], "WWII", "34-60"),
    new Brick("GERALD K", "MOYER", "ARMY", [1], "KOREAN WAR", "39-58"),
    new Brick("GEORGE R", "LESLIE", "ARMY", [1], "WWII", "43-64"),
    new Brick("BUTCH", "VONADA", "AIR FORCE", [3], "", "44-64"),
    new Brick("LARRY L", "BARBOUR", "ARMY", [1], "PERSIAN GULF", "45-61"),
    new Brick("ROBERT", "KEENE", "MARINE CORPS", [4], "VIETNAM WAR", "49-63"),
    new Brick("GEORGE", "MOCK", "COAST GUARD", [5], "VIETNAM WAR", "49-65"),
    new Brick("FRED O", "BENNER", "ARMY", [1], "KOREAN WAR", "51-64"),
    new Brick("RUSSELL", "SPADE", "ARMY", [1], "WWII", "55-66"),
    new Brick("HAROLD", "STITZER", "ARMY", [1], "WWII", "56-60"),
    new Brick("MAX O", "FULTZ", "ARMY", [1], "WWII", "51-60"),
    new Brick("RICHARD", "DUNKLE", "ARMY", [1], "VIETNAM WAR", "44-58"),
    new Brick("BLAINE J", "DUNKLE", "ARMY", [1], "WWII", "43-58"),
    new Brick("HAROLD E", "GRAMLEY", "AIR FORCE", [3], "", "47-56"),
    new Brick("RON", "SUMMERS", "MARINE CORPS & ARMY", [4, 1], "VIETNAM WAR", "48-53"),
    new Brick("EDGAR A", "TREASTER", "NAVY", [2], "VIETNAM WAR", "53-55"),
    new Brick("CLARENCE", "CRATER", "ARMY", [1], "WWII", "53-53"),
    new Brick("C S", "HOSTERMAN JR", "ARMY AIR CORPS", [6], "WWII", "43-54"),
    new Brick("RAYMOND", "MUSSER", "ARMY", [1], "", "46-51"),
    new Brick("RUSS", "SCHLEIDEN", "AIR FORCE", [3], "VIETNAM WAR", "52-50"),
    new Brick("RONALD", "SCHAEFFER", "ARMY", [1], "VIETNAM WAR", "51-48"),
    new Brick("RYAN A", "HELTMAN", "ARMY", [1], "", "46-47"),
    new Brick("BEN C", "BAILEY", "ARMY AIR CORPS", [6], "WWII", "59-48"),
    new Brick("WAYNE K", "MILLER", "ARMY", [1], "VIETNAM WAR", "60-46"),
    new Brick("CHARLES", "HASSINGER, SR", "ARMY", [1], "", "63-46"),
    new Brick("FRANKLIN", "CARPER", "ARMY", [1], "", "60-42"),
    new Brick("TIMOTHY", "ARCHER", "AIR FORCE", [3], "", "67-48"),
    new Brick("JOHN W", "PUFF", "MARINE CORPS", [4], "WWII", "69-51"),
    new Brick("BOWIE", "MILLER", "ARMY", [1], "IRAQI FREEDOM", "71-48"),
    new Brick("MELVIN", "HOLLIER", "ARMY", [1], "WWII", "73-53"),
    new Brick("CHARLES", "WINGARD", "ARMY AIR CORPS", [6], "WWII", "76-50"),
    new Brick("TORRENCE", "BARNER", "AIR FORCE", [3], "VIETNAM WAR", "77-55"),
    new Brick("ALLEN W", "LEASE", "NAVY", [2], "", "76-58"),
    new Brick("GUST J", "MADERIA", "AIR FORCE", [3], "KOREAN WAR", "71-58"),
    new Brick("HARRY", "HASSINGER", "NAVY & AIR FORCE", [2, 3], "WWII & KOREAN WAR", "73-65"),
    new Brick("JOHN R", "MERSINGER", "AIR FORCE", [3], "VIETNAM ERA IS", "69-69"),
    new Brick("HARRY C", "VANADA JR", "ARMY", [1], "KOREAN WAR", "74-69"),
    new Brick("JAMES H", "WILSON", "MARINE CORPS", [4], "", "78-69"),
    new Brick("ROBERT D", "SMITH", "NAVY", [2], "KOREAN WAR", "74-47"),
    new Brick("CHARLES", "ANDERSON JR", "AIR FORCE", [3], "", "72-44"),
    new Brick("CHARLES", "ANDERSON", "ARMY", [1], "WWII", "71-44"),
    new Brick("THOMAS", "ANDERSON", "ARMY", [1], "VIETNAM WAR", "70-43"),
    new Brick("ROBERT", "ANDERSON", "ARMY", [1], "VIETNAM WAR", "69-43"),
    new Brick("STEPHEN", "ANDERSON", "MARINE CORPS", [4], "", "70-42"),
    new Brick("KIMBERLY A", "RIMMEY", "ARMY", [1], "IRAQI FREEDOM", "75-44"),
    new Brick("NEVIN G", "HOMAN", "MARINE CORPS", [4], "VIETNAM WAR", "77-39"),
    new Brick("DAVE I", "GRAYBILL", "ARMY", [1], "WWII", "69-39"),
    new Brick("JIM", "HIRONIMUS", "AIR FORCE", [3], "VIETNAM WAR", "74-35"),
    new Brick("CHUCK", "NORRIS", "ARMY", [1], "VIETNAM WAR", "75-32"),
    new Brick("KEITH", "NORRIS SR", "ARMY", [1], "VIETNAM WAR", "76-32"),
    new Brick("NEVIN", "WALTERS", "ARMY", [1], "WWII", "77-32"),
    new Brick("ROBERT", "WALTERS SR", "AIR FORCE", [3], "VIETNAM WAR", "76-31"),
    new Brick("RALPH L", "SHOPE JR", "ARMY", [1], "KOREAN WAR", "68-34"),
    new Brick("WILLIAM B", "HOMAN", "MARINE CORPS", [4], "VIETNAM WAR", "77-27"),
    new Brick("RUSSELL", "LEONARD", "ARMY", [1], "VIETNAM WAR", "66-29"),
    new Brick("GRIER C", "BARBOUR", "AIR AIR CORPS", [3], "WWII", "61-31"),
    new Brick("CAROL A", "CLARK-BANEY", "ARMY", [1], "", "58-33"),
    new Brick("IRWIN", "RHODE", "MARINE CORPS", [4], "VIETNAM WAR", "58-29"),
    new Brick("THOMAS", "HEVERLY", "NAVY", [2], "VIETNAM WAR", "54-29"),
    new Brick("LLOYD L", "WENRICK", "ARMY", [1], "VIETNAM WAR", "52-28"),
    new Brick("THOMAS S", "STONER", "ARMY", [1], "", "47-30"),
    new Brick("HAROLD", "SAMPSELL", "ARMY", [1], "VIETNAM WAR", "46-29"),
    new Brick("PHILIP", "BRADFORD", "ARMY", [1], "KOREAN WAR", "40-22"),
    new Brick("HAROLD", "BRADFORD", "NAVY", [2], "WWII", "39-22"),
    new Brick("JAMES D", "YOUNG", "NAVY", [2], "WWII & KOREAN WAR", "41-25"),
    new Brick("C L", "PRICE", "NAVY", [2], "WWII", "41-27"),
    new Brick("DENNIS", "PRICE", "NAVY", [2], "VIETNAM WAR", "42-27"),
    new Brick("MARVIN", "PRICE", "NAVY", [2], "WWII", "43-28"),
    new Brick("EUGENE I", "PRICE", "MARINE CORPS", [4], "WWII", "40-27"),
    new Brick("WILLIAM W", "STUTER", "MARINE CORPS", [4], "", "41-28"),
    new Brick("R DALE", "SHIELDS", "ARMY AIR CORPS", [6], "WWII", "42-28"),
    new Brick("WILLIAM C", "SCHULTZ", "ARMY", [1], "KOREAN WAR", "40-19"),
    new Brick("JAMES M", "COLE", "ARMY", [1], "", "37-19"),
    new Brick("VINTON H", "LINGLE", "NAVY", [2], "WWII", "35-22"),
    new Brick("MAHLON", "McMURTRIE", "MARINE CORPS", [4], "VIETNAM WAR", "34-25"),
    new Brick("KENNETH E", "HAUPT SR", "ARMY", [1], "KOREAN WAR", "29-27"),
    new Brick("LARRY H", "YOUNG", "ARMY", [1], "VIETNAM WAR", "32-28"),
    new Brick("KEN", "SPANGLER", "ARMY", [1], "VIETNAM WAR", "33-29"),
    new Brick("BUDD L", "HOY", "ARMY", [1], "WWII & KOREAN WAR", "24-28"),
    new Brick("WALTER", "MAYES", "MARINE CORPS", [4], "KOREAN WAR", "18-31"),
    new Brick("MICHAEL", "MAYES", "ARMY", [1], "IRAQI FREEDOM", "19-32"),
    new Brick("RONALD", "MAYES SR", "USMC", [4], "VIETNAM ERA", "20-32"),
    new Brick("DONALD R", "MAYES", "ARMY", [1], "KOREAN WAR", "21-33"),
    new Brick("KENNETH", "BOWER", "AIR FORCE", [3], "KOREAN WAR", "20-34"),
    new Brick("RALPH E", "LONG", "ARMY", [1], "WWII", "18-37"),
    new Brick("DONALD", "FETTEROLF", "AIR FORCE", [3], "KOREAN WAR", "20-38"),
    new Brick("DENNIS W", "ROYER", "ARMY", [1], "VIETNAM WAR", "21-38"),
    new Brick("GLENN C", "DERSHEM", "NAVY", [2], "WWII", "21-39"),
    new Brick("WILLARD T", "ROYER", "ARMY", [1], "WWII", "19-39"),
    new Brick("GEARHARD", "ROYER", "ARMY", [1], "", "20-39"),
    new Brick("JUSTIN", "WITHERITE", "ARMY", [1], "", "12-39"),
    new Brick("HARRY M", "BROWN", "ARMY", [1], "WWII", "13-40"),
    new Brick("ROY C", "HOMAN", "ARMY", [1], "", "13-41"),
    new Brick("LEWIS", "GARBRICK", "NAVY", [2], "WWII", "18-43"),
    new Brick("FRED", "BURLINGAME", "ARMY AIR CORPS", [6], "WWII", "20-46"),
    new Brick("CHARLES H", "ORT", "NAVY", [2], "WWII", "25-47"),
    new Brick("C EUGENE", "DUTROW", "ARMY", [1], "KOREAN WAR", "27-44"),
    new Brick("WILLIAM", "ALLISON", "NAVY", [2], "VIETNAM WAR", "22-49"),
    new Brick("LEE S", "HALL", "ARMY", [1], "WWII", "29-47"),
    new Brick("A R", "McNITT", "ARMY", [1], "KOREAN WAR", "30-47"),
    new Brick("JOHN D", "KNARR", "ARMY", [1], "WWII", "31-48"),
    new Brick("PHILLIP", "CRAUL", "ARMY", [1], "", "27-49"),
    new Brick("LARRY R", "MOYER", "AIR FORCE", [3], "VIETNAM WAR", "29-51"),
    new Brick("CLARENCE", "OAKES", "MARINE CORPS", [4], "VIETNAM WAR", "30-53"),
    new Brick("JOHN", "NWRANSKI", "ARMY", [1], "WWII", "33-51"),
    new Brick("MICHAEL", "MUSSER", "AIR FORCE", [3], "PERSIAN GULF", "34-54"),
    new Brick("RICHARD", "RUNKLE", "AIR FORCE", [3], "KOREAN WAR", "33-56"),
    new Brick("RICHARD E", "SMALLEY", "ARMY", [1], "KOREAN WAR", "38-53"),
    new Brick("J E", "CHIOVAROU", "NAVY", [2], "", "42-49"),
    new Brick("MICHAEL", "WENRICK", "ARMY", [1], "IRAQI FREEDOM", "52-44"),
    new Brick("W", "WENRICK", "ARMY", [1], "", "53-45"),
    new Brick("MAURICE", "NEWMAN", "MARINE CORPS", [4], "VIETNAM WAR", "54-45"),
    new Brick("CLYDE", "BOYER", "ARMY", [1], "WWII", "55-46"),
    new Brick("NICK", "LESNIAK", "ARMY", [1], "", "49-43"),
    new Brick("STAN", "LESNIAK", "ARMY & NAVY", [1, 2], "", "50-42"),
    new Brick("MICHAEL P", "McDERMOTT", "NAVY", [2], "", "67-42"),
    new Brick("MIKE", "McCLENAHAN", "ARMY", [1], "KOREAN WAR", "64-40"),
    new Brick("ROBIN", "McCLENAHAN", "ARMY", [1], "", "63-40"),
    new Brick("PAT", "McCLENAHAN", "ARMY", [1], "", "63-39"),
    new Brick("MILES W", "WOLFE", "ARMY", [1], "WWII", "64-39"),
    new Brick("TERRY L", "ALEXANDER", "ARMY", [1], "VIETNAM WAR", "62-37"),
    new Brick("TIM TR", "ROSS", "ARMY", [1], "VIETNAM ERA", "51-31"),
    new Brick("ROBERT S", "ROSS", "ARMY AIR CORPS", [6], "WWII", "50-31"),
    new Brick("ARDELL", "GROSS SR", "NAVY", [2], "WWII", "51-32"),
    new Brick("JOHN I", "STONER", "ARMY", [1], "VIETNAM WAR", "42-31"),
    new Brick("LEWIS A", "CRADER", "ARMY", [1], "WWI", "38-32"),
    new Brick("HAROLD", "WINGARD", "AIR FORCE", [3], "VIETNAM WAR", "40-32"),
    new Brick("DOYLE", "WINGARD", "NAVY", [2], "WWII", "39-33"),
    new Brick("HENRY", "WINGARD", "ARMY", [1], "WWII", "41-33"),
    new Brick("JAY", "WINGARD", "ARMY AIR CORPS", [6], "WWII", "42-33"),
    new Brick("STUART", "WINGARD", "ARMY", [1], "WWII", "43-34"),
    new Brick("ALLEN R", "WINGARD", "ARMY", [1], "WWI", "44-34"),
    new Brick("TIMOTH R", "LAKE", "NAVY", [2], "PERSIAN GULF", "36-32"),
    new Brick("MIKE", "LAKE", "ARMY", [1], "VIETNAM WAR", "35-32"),
    new Brick("ROY K", "DUNKLEBARGER", "ARMY", [1], "WWII", "33-31"),
    new Brick("GEO RUSS", "SMITH", "AIR FORCE", [3], "KOREAN WAR", "30-31"),
    new Brick("LEE C", "DORMAN", "NAVY", [2], "", "24-32"),
    new Brick("NEVIN E", "LONG", "ARMY", [1], "", "23-35"),
    new Brick("RAYMOND", "MUSSER", "ARMY", [1], "WWII", "26-37"),
    new Brick("STEPHEN L", "FOUST", "ARMY", [1], "VIETNAM ERA", "30-39"),
    new Brick("GLENN", "BRESSLER", "ARMY", [1], "WWII", "33-35"),
    new Brick("DENNIS", "BRESSLER", "ARMY", [1], "VIETNAM WAR", "34-35"),
    new Brick("JAMES V", "SWALES", "ARMY", [1], "WWII", "35-36"),
    new Brick("RONALD J", "HORNER", "ARMY", [1], "VIETNAM WAR", "33-41"),
    new Brick("DENNIS", "ROYER", "AIR FORCE", [3], "", "34-43"),
    new Brick("DEAN B", "RIPKA", "ARMY", [1], "WWII", "35-44"),
    new Brick("KENNETH D", "ROYER", "AIR FORCE", [3], "VIETNAM WAR", "36-44"),
    new Brick("PAUL A", "GROVE", "ARMY", [1], "WWII", "37-45"),
    new Brick("CARL W", "ROYER", "AIR FORCE", [3], "KOREAN WAR", "38-45"),
    new Brick("SHANE", "ROYER", "ARMY", [1], "PERSIAN GULF", "39-46"),
    new Brick("SHANE", "ROYER", "ARMY", [1], "IRAQI FREEDOM", "40-46"),
    new Brick("ARTHUR", "RIDENOUR SR", "MARINE CORPS", [4], "VIETNAM WAR", "41-45"),
    new Brick("TERRY", "CHAMBERLIN", "ARMY", [1], "VIETNAM ERA", "38-49"),
    new Brick("MAHLON D", "NEVEL", "ARMY", [1], "WWII", "45-43"),
    new Brick("WILLIAM E", "MILLS", "ARMY", [1], "VIETNAM WAR", "49-41"),
    new Brick("ARDEL H", "VONADA", "ARMY AIR CORPS", [6], "WWII", "48-38"),
    new Brick("HOBIE", "KISTLER", "NAVY", [2], "NAVAL REACTORS", "50-37"),
    new Brick("STEPHEN", "KUCAS", "ARMY", [1], "KOREAN WAR & VIETNAM WAR", "48-36"),
    new Brick("MICHAEL", "KRONER", "ARMY", [1], "IRAQI FREEDOM", "46-37"),
    new Brick("CHESTER", "PLETCHER", "ARMY", [1], "WWII", "44-38"),
    new Brick("HAROLD W", "SMITH", "ARMY AIR CORPS", [6], "WWII", "44-36"),

    new Brick("CHUCK", "GRUBB", "ARMY", [1], "VIETNAM WAR", "49-8"),
    new Brick("LEON", "STINGER", "ARMY", [1], "KOREAN WAR", "37-10"),
    new Brick("TOM", "BREON", "AIR FORCE", [3], "VIETNAM WAR", "24-19"),
    new Brick("STEPHEN", "ZELZNICK", "MARINE CORPS", [4], "", "20-23"),
    new Brick("KEVIN", "LONG", "ARMY", [1], "", "26-31"),
    new Brick("KERRY", "HORNER", "ARMY", [1], "LEBANON/GRENADA", "23-27"),
    new Brick("MIKE", "BLOOM", "MARINE CORPS", [4], "VIETNAM WAR", "31-19"),
    new Brick("ROBERT LEE", "BLOOM", "MARINE CORPS", [4], "", "32-19"),
    new Brick("G. H.", "JOHNSTONBAUGH", "ARMY", [1], "KOREAN WAR", "33-20"),
    new Brick("WILLIAM R.", "GUZIK", "AIR FORCE", [3], "KOREAN WAR", "34-20"),
    new Brick("CHRISTIAN", "FEIT", "NAVY", [2], "VIETNAM WAR", "49-37"),

    new Brick("MARILYN A", "KUBALAK", "ARMY NURSE CORPS", [8], "VIETNAM WAR", "24-55"),
    new Brick("JOHN L", "KUBALAK", "ARMY", [1], "VIETNAM WAR", "24-56"),
    new Brick("ALBERT", "MIHALIC", "ARMY", [1], "WWII", "25-56"),
    new Brick("JOHN R", "KUBALAK", "ARMY", [1], "WW", "25-57"),
    new Brick("JEFF", "BATHGATE", "ARMY", [1], "VIETNAM WAR", "26-56"),
    new Brick("CHARLES", "GREGORY", "MARINE CORPS", [4], "VIETNAM WAR", "21-41"),
    new Brick("PAUL", "MAYNARD", "MARINE CORPS", [4], "VIETNAM WAR", "20-41"),
    new Brick("LLOYD", "MULVIHILL", "NAVY", [2], "WWII", "20-42"),
    new Brick("ROBERT", "MOORE", "NAVY", [2], "VIETNAM WAR", "19-42"),
    new Brick("DONALD", "STOVER", "MARINE CORPS", [4], "VIETNAM WAR", "19-41"),
    new Brick("CAROL", "FREELAND", "ARMY", [1], "LEBANON/GRENADA", "18-41"),
    new Brick("ALBERT", "MOORE", "AIR FORCE", [3], "VIETNAM WAR", "17-42"),
    new Brick("HILDA", "PUTNAM", "ARMY", [1], "LEBANON/GRENADA", "17-41"),
    new Brick("MYRON", "TESSENA", "MARINE CORPS", [4], "VIETNAM WAR", "17-40"),
    new Brick("TERRY", "TESSENA", "MARINE CORPS", [4], "VIETNAM WAR", "18-40"),
    new Brick("DAVID", "PUTNAM", "NAVY", [2], "VIETNAM WAR", "16-41"),
    new Brick("JOHN", "PUTNAM", "NAVY", [2], "WWII & KOREAN WAR", "15-41"),
    new Brick("ROBERT", "McKEIRNAN", "NAVY", [2], "WWII", "16-40"),
    new Brick("MICKEY", "McKEIRNAN", "NAVY", [2], "WWII", "16-39"),
    new Brick("D ELLIS", "LANDIS", "ARMY", [1], "KOREAN WAR", "28-42"),
    new Brick("ELVIN J", "LANDIS", "ARMY", [1], "", "29-42"),
    new Brick("WESLEY M", "LANDIS", "ARMY", [1], "VIETNAM WAR", "29-43"),
    new Brick("CHARLES R", "ROWLES", "ARMY", [1], "WWII", "31-43"),
    new Brick("DONALD C", "MILLER", "NAVY & MARINE CORPS", [2, 4], "WWII & KOREAN WAR & VIETNAM WAR", "32-42"),
    new Brick("JOSEPH D", "SLENKER", "ARMY AIR CORPS", [6], "WWII", "27-34"),
    new Brick("ELWOOD F", "FOHRINGER", "ARMY", [1], "WWII", "28-34"),
];

BRICKS.sort(
    (a, b) =>
        a.lname.localeCompare(b.lname) ||
        a.fname.localeCompare(b.fname) ||
        a.branch.localeCompare(b.branch) ||
        a.conflict.localeCompare(b.conflict)
);

const COORDS = new Set(BRICKS.map((b) => b.coords));

const brickHeight = 4,
    brickWidth = 8,
    brickColor = "#eb9b4b",
    brickColor2 = "#bc6915",
    edgeColor = "gray",
    brickHighlightColor = "#39ff14",
    brickOutlineColor = "#000";
